# Generated by Django 2.1.2 on 2018-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercuryManometerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=50)),
                ('Differential_Pressure', models.CharField(max_length=50)),
                ('Weir_Height', models.CharField(max_length=50)),
                ('Upstream_Pressure', models.CharField(max_length=50)),
                ('Steam_flow_rate', models.CharField(max_length=50)),
                ('Corr_Water_flow', models.CharField(max_length=50)),
                ('Mass_Flow_rate', models.CharField(max_length=50)),
                ('Stream_enthalpy', models.CharField(max_length=50)),
                ('combined_enthalpy', models.CharField(max_length=50)),
                ('Whp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'MercuryManometerTable',
            },
        ),
    ]
