# Generated by Django 2.1.2 on 2018-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryManometer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Corr_Water_flow',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Differential_Pressure',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Mass_Flow_rate',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Steam_flow_rate',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Stream_enthalpy',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Upstream_Pressure',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Weir_Height',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Whp',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='combined_enthalpy',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
    ]
