# Generated by Django 2.1.2 on 2018-10-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryManometer', '0002_auto_20181025_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Corr_Water_flow',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Differential_Pressure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Mass_Flow_rate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Steam_flow_rate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Stream_enthalpy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Upstream_Pressure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Weir_Height',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='Whp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mercurymanometertable',
            name='combined_enthalpy',
            field=models.CharField(max_length=50),
        ),
    ]
