# Generated by Django 2.1.2 on 2018-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumericalModelingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('Flow_Rate', models.CharField(max_length=50)),
                ('Totals', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'NumericalModelingTable',
            },
        ),
    ]
